describe('register user', () => {
    it('rgistering user detail', () => {
      cy.visit("https://automationexercise.com/")
      // cy.get('.active > :nth-child(1) > h2').should('have.value', 'Full-Fledged practice website for Automation Engineers')
      // cy.wait(1000)
      cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
      cy.get('[data-qa="signup-name"]').type('testor')
      cy.get('[data-qa="signup-email"]').type('testingnamo@gmail.com')
      cy.get('[data-qa="signup-button"]').click()

     // cy.get(':nth-child(1) > b').should('have.value','ENTER ACCOUNT INFORMATION')
     cy.get('#id_gender2').check().should('have.checked')
     cy.get('[data-qa="password"]').type('Test@1234')
    // cy.get('[data-qa="days"]').should('have.vlaue', '12').click()
   //  cy.get('[data-qa="months"]')
    //  cy.get('[data-qa="years"]')
     cy.get('#newsletter').check()
     cy.get('#optin').check()
    cy.get('[data-qa="first_name"]').type('namrata')
     cy.get('[data-qa="last_name"]').type('gaur')
     cy.get('[data-qa="company"]').type('tcs')
     cy.get('[data-qa="address"]').type('aligarh')
     cy.get('[data-qa="address2"]').type('noida')
    cy.get('[data-qa="state"]').type('uttar pradesh')
    cy.get('[data-qa="city"]').type('ghaziabaad')
     cy.get('[data-qa="zipcode"]').type('12345678')
    cy.get('[data-qa="mobile_number"]').type('1234567890')
    cy.get('[data-qa ="create-account"]').click()
    cy.get('b').contains('Account Created')
    cy.get('[data-qa="continue-button"]').click()
    cy.get(':nth-child(10) > a').should('be.visible')
    // cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
    // cy.get('b').contains('Account Deleted')
    // cy.get('[data-qa="continue-button"]').click()
    })
  })

  //task pending validations and prompt of no thanks page and date select tab 